### PR TITLE
Hide expired user entries when a list of vacations has been requested

### PR DESCRIPTION
**Pull request by Haarolean**
That's a minimal fix, ofc. We could invalidate entries in database, or even clean them up periodically.

### CODE REVIEW

**Comment by Kunpero** [comment]
idk, i think that it's better to show information about past vacations to user. Maybe in other form, so he would be aware of how many vacation days are left.

**Comment by Haarolean** [comment]
@Kunpero while there's no such a feature, how about we just hide such entries? They're still present in the database, just not being shown.

**Comment by vrnsky** [comment]
LGTM, but we need to extend the data transfer object for flexibility reason. Because of some of the users, would like to see past and current, and future vacations. By default expired should be hidden.
I think it is a good idea to provide some flags like:
`--show-expired --month`

**Review by vrnsky — APPROVED** [review]

**Comment by Kunpero** [comment]
@Haarolean Thank you for that enhancement!

> LGTM, but we need to extend the data transfer object for flexibility reason. Because of some of the users, would like to see past and current, and future vacations. By default expired should be hidden.
> I think it is a good idea to provide some flags like:
> `--show-expired --month`

@vrnsky Exactly, currently I'm working on the issue you've noticed.

**Pull request merged**
